local로그인 구현
HelloTutor/HelloTutor-BE pull request #14
Opened 2023-12-23 13:07 UTC by moonhuicheol

- refreshToken을 db에 저장후 accessToken재발급할때 req에서 보낸 refreshToken과 db에 있는 refreshToken을 비교한 후에 재발급해야하는지 궁금합니다.
 
 - 코드 syntax와 불필요한 코드 또는 부족한 부분이 있는지 확인 부탁드립니다!

2023-12-23 14:43 UTC, zero2080 commented
### 1. 회원가입 불가
  - `bcrypt`를 통한 해쉬화의 길이는 길이가 60으로 고정입니다.
  - 컬럼길이가 50이어서 길이가 60인 패스워드가 저장되지 않습니다.
  - `NOT NULL` 조건때문에 가입진행이 되지 않습니다.
    - `tb_user` 테이블의 여러컬럼의 `NOT NULL` 조건을 확인해 주세요. 해당 조건의 컬럼들때문에 가입진행이 불가합니다.

### 2. 로그인 불가
  - 토큰 발급 로직 재검토

2023-12-23 14:44 UTC, zero2080 reviewed
좀더 세밀한 테스트습관을 들이세요.

토큰 유효시간을 짧게 설정하고 테스트 해보세요.

2023-12-23 14:44 UTC, zero2080 commented on middleware/authorization.js
> +            exp: "14d"
`exp` > `expiresIn` 으로 변경

2023-12-23 14:44 UTC, zero2080 commented on middleware/authorization.js
> +            exp: "1h"
`exp` > `expiresIn` 으로 변경

2023-12-23 14:44 UTC, zero2080 commented on middleware/authorization.js
> +    //accessToken, refreshToken 둘다 expired 일때
존재 여부만 체크하는데 어떻게 `expired` 이죠?

2023-12-23 14:44 UTC, zero2080 commented on middleware/authorization.js
> +    return jwt.verify(token, secret_key);
토큰이 만료되면 `jwt.verify` 메서드에서 `TokenExpiredError` 예외를 발생시킵니다.

2023-12-25 11:41 UTC, moonhuicheol commented
tb_user 수정했습니다. 수정했었는데 이상하게.. 이전 버전으로 들어가있네요..
jwt 토큰 accessToken, refreshToken 응답 확인했습니다. 
추후에 다른 api 개발할때 토큰 주기를 줄여 재발급 까지 확인해보도록 하겠습니다.

2023-12-25 18:07 UTC, zero2080 requested changes
- [ ] 불필요 함수 제거
- [ ] 토큰 파싱 함수 수정
- [ ] `res.send` -> `res.json` 변경
- [ ] 응답 전송 후 불필요한 연산 종료 (`return` )

2023-12-25 18:07 UTC, zero2080 commented on middleware/authorization.js
> +        res.status(400).send({ message: "잘못된 비밀번호 입니다."});
```suggestion
        return res.status(400).json({ message: "잘못된 비밀번호 입니다."});
```
1. 함수 종료를 통해 추가 로직이 수행되지않게 끊어주세요.
2. json메서드를 통해 응답 헤더의 content-type이 application/json이 설정되게 하는걸 추천드립니다.

2023-12-25 18:07 UTC, zero2080 commented on middleware/authorization.js
> +    //accessToken, refreshToken 둘다 expired 일때
> 존재 여부만 체크하는데 어떻게 `expired` 이죠?

expiresIn을 1s로 수정해서 테스트해보면 금방알수있습니다. 해보세요.

2023-12-25 18:07 UTC, zero2080 commented on middleware/authorization.js
> +    const accessToken = checkExpiredToken(req.headers["Authorization"]);
```suggestion
    const accessToken = checkExpiredToken(req.headers("Authorization"), ACCESS_PRIVATE_KEY);
```

- 헤더값 가져올땐 소괄호
- 두번째인자 누락

2023-12-25 18:07 UTC, zero2080 commented on middleware/authorization.js
> +    const refreshToken = checkExpiredToken(req.headers["RefreshToken"]);
```suggestion
    const refreshToken = checkExpiredToken(req.headers("RefreshToken"), REFRESH_PRIVATE_KEY);
```

- 헤더값 가져올땐 소괄호
- 두번째인자 누락

2023-12-25 18:07 UTC, zero2080 commented on middleware/authorization.js
> +function checkExpiredToken(token) {
```suggestion
function checkExpiredToken(token,secret) {
```

검증 혹은 파싱하려면 토큰을 생성할때 키가 반드시 필요합니다.

2023-12-25 18:07 UTC, zero2080 commented on middleware/authorization.js
> +        let decodedToken = verifyToken(token);
```suggestion
        let decodedToken = jwt.verify(token,secret);
```

`verifyToken`메서드와 내용이 거의 같으니 이쪽으로 통합하는게 나을것같습니다.

2023-12-25 18:07 UTC, zero2080 commented on middleware/authorization.js
> +        }
```suggestion
        return decodedToken;
```

어차피 파싱한 걀과값을쓸건데 정상파싱된건 그냥 써도 됭듯합니다

2023-12-25 18:07 UTC, zero2080 commented on middleware/authorization.js
> +}
```suggestion
```
제거해도 될듯합니다
아래 함수와 내용이 거의 동일합니다

2023-12-25 18:07 UTC, zero2080 commented on middleware/authorization.js
> +    if (accessToken === "TokenExpiredError" && refreshToken === false) {
```suggestion
    if (accessToken === "TokenExpiredError" && refreshToken) {
```
리프레시 토큰이 아직 유효할때가 구지 `boolean`타입일 필요는 없는것 같습니다

2023-12-25 18:07 UTC, zero2080 commented on middleware/authorization.js
> +        const newAccessToken = generateAccessToken(parseRefreshToken.id, parseRefreshToken.email, parseRefreshToken.status);
```suggestion 
        const newAccessToken = generateAccessToken(refreshToken.id, refreshToken.email, refreshToken.status);
```

2023-12-25 18:07 UTC, zero2080 commented on middleware/authorization.js
> +    if (accessToken === false && refreshToken === "TokenExpriedError") {
```suggestion
    if (accessToken 
 && refreshToken === "TokenExpriedError") {
```
객체가 만료가 안됐다면 파싱한 결과를 담고있을겁니다

2023-12-25 18:07 UTC, zero2080 commented on schema/userTable.sql
> +	`role` int DEFAULT NULL,
```suggestion
	`role` int NOT NULL,
```
낫널 조건을 두는게 맞지않나요? 역할컬럼은 필수니까요

2023-12-25 18:07 UTC, zero2080 commented on middleware/authorization.js
> +        res.status(400).send( {message: "해당 이메일이 없습니다."});
```suggestion
        return res.status(400).json( {message: "해당 이메일이 없습니다."});
```

1. 함수 종료를 통해 추가 로직이 수행되지않게 끊어주세요.
2. json메서드를 통해 응답 헤더의 content-type이 application/json이 설정되게 하는걸 추천드립니다.

2023-12-26 07:28 UTC, moonhuicheol commented
토큰 재발급 모두 확인했습니다.

2023-12-26 07:32 UTC, zero2080 approved these changes
sql파일에 콤마와 세미콜론때문에 오류 발생여지가 좀 있긴하네요.
나머지는 다음 기능에서 수정합시다.
고생하셨습니다.

2023-12-28 11:38 UTC, merged