Freeboard
HelloTutor/HelloTutor-BE pull request #24
Opened 2024-01-10 14:17 UTC by moonhuicheol

1. 프로필사진은 추후에 구현하도록하겠습니다.
2. 검색기능을 구현하였지만 효율적인 검색까지는 고민하지 못했습니다.(시간 ㅜㅜ)

2024-01-10 18:23 UTC, zero2080 reviewed
1. 테스트 코드 삭제 
  - `/del` 요청
2. 분기를 나눌때 되도록이면 한 도메인으로 처리가 가능하면 분리하지 않는걸 추천합니다.
  - `/board` 로 시작하는 도메인이라면 아래와 같이 목적에 맞게 분기하면 나중에 찾기도 편할겁니다.
    -  `index.js`
        ```
        app.use('/board',board);
        ```
    - `/router/board.js`
        ```
        router.use('/free',freeboard);
        ```
    - `/router/freeboard.js`
        ```
        router.get('/:id',selectFreeBoard);
        ...
        router.use('/:id/comment',freeBoardComments);
        ```
3. 회원가입에서 비밀번호가 틀렸다고 리턴될 것으로 보입니다.
4. `insert` 쿼리의 응답 데이터로 검증하는것은 좋은데 오류없이 `affectedRows`값이 1보다 크거나 작을때의 로직이 없습니다. 논리적으로 해당 상황은 없을것같긴하나 혹시 모르니 염두는 해주시기 바랍니다.
5. 오류 발생시 콘솔로그로 출력하고 응답을 전달하지 않습니다.
    - `/repository/freeBoardRepository.js`
6. 구조 제할당을 적극 활용해 주세요~~
  ```
  let { page } = req.query;
  let { pageSize } = req.query;
  let { search } = req.query;

  let { page,pageSize,search } = req.query;
  ```
8. `limit` 도 문자열로 치환해주세요~
9. 목록조회에서 `content` 컬럼은 필요 없지 않나요?
10. 트랜젝션단위로 작업을 처리하고 싶다면 `try/catch` 만으로 롤백하고 끝내는게 아니라 커넥션풀에 사용한 커넥션을 반환해줘야 합니다. `conn.release();` !!!! 중요 !!!!
11. 댓글에서 `role`은 왜??
12. 쿼리에서 함수를 통해 생성한 컬럼은 이름을 지정해 주세요 ex) `COUNT(l.user_id) AS like_cound`

2024-01-11 02:56 UTC, moonhuicheol commented
3. 테스트 해봤는데 비밀번호 8자리 이상, 정규식 통과하면 가입 되긴하는데 어느부분이 문제인지 확인하지 못했습니다.
5. repository에 있는 함수 파라미터에 res를 받지 않아서 응답처리하지않고, 해당 함수를 사용하는 controller에서 응답처리했는데 이렇게 하면 안될까요??
11. figma보시면 댓글에서 tutee, tutor를 확인할 수 있도록 계획하긴했는데 수정할까요??

2024-01-11 04:06 UTC, zero2080 reviewed
- 가입시 비밀번호 확인 필드가 추가됐다는걸 이제 알았네요.
- 오류가 발생했을때 함수를 호출한쪽에서 처리하고싶다면 호출한 함수로 throw해야 합니다.
- 모든 연결의 커넥션을 반환해 주세요.
- url path가 변경되면 api문서에도 반영해 주세요( 확인은 하지 않았습니다. )

ps. 테스트는 꼼꼼하게~

2024-01-11 04:06 UTC, zero2080 commented on controller/free_Board_Comments.controller.js
> +        }
만약 A유저가 본인의 토큰으로 B의 게시글을 수정하려고 한다면  
오류는 발생하지 않고 return도 없고 응답도 없이 함수가 종료됩니다.
이럴때 서버는 응답을 보내지 않은상태로 연결을 유지 합니다.
```suggestion
        if (decodedToken.id === selectRow.user_id) {
            const { body } = req;
            const updateRow = await freeBoardCommentsRepository.updateFreeBoardComments(decodedToken, postId, commentId, body);

            if (updateRow.affectedRows === 1) {
                return res.status(200).json({ message: "댓글 수정 완료" });
            }
        }else{
            return res.status(403).json({ message: "수정권한이 없습니다" });
        }
```

2024-01-11 04:06 UTC, zero2080 commented on controller/free_Board_Comments.controller.js
> +        }
여기도 마찬가지 입니다.

2024-01-11 04:06 UTC, zero2080 commented on controller/free_Board_Comments.controller.js
> +        const limit = String(pageSize);
`req.params` 의 데이터타입은 전부 **문자열**입니다.

2024-01-11 04:06 UTC, zero2080 commented on controller/free_board.controller.js
> +        }
여기도 요청자가 응답을 기다리는 동안 서버와 연결이 유지 됩니다.

```suggestion
                if (decodedToken.id === selectRow.user_id) {
	            const { body } = req;
	            const updateRow = await freeBoardRepository.updateFreeBoard(decodedToken, postId, body);
	
	            if (updateRow.affectedRows === 1) {
	                return res.status(200).json({ message: "게시글 수정 완료" });
	            }
	        }else{
	            return res.status(403).json({ message: "권한이 없습니다"});
	        }
```

2024-01-11 04:06 UTC, zero2080 commented on controller/free_board.controller.js
> +        }
여기도

2024-01-11 04:06 UTC, zero2080 commented on controller/like.controller.js
> +        }
여기도

2024-01-11 04:06 UTC, zero2080 commented on repository/freeBoardCommentsRepository.js
> +        console.log(error);
이렇게 끝내면 발생한 에러를 전달하지 않고 함수가 끝납니다.
```suggestion
        console.log(error);
        throw error;
```

`throw`를 해야 자기를 호출한 함수에 오류가 발생한 내역을 전달합니다. 
그제서야 이 함수를 호출한 try블록 안에서 `catch`로 다시 전달받은 오류를 전달합니다.

나머지 try/catch 도 전부 마찬가지 이며, 그렇다고 부분별하게 던지면 안됩니다.
기능의 끝나는 지점, 오류를 전달해야하는 상황, 전체 로직에서의 중단지점을 전부 이해하고 판단해야 합니다.

2024-01-11 04:06 UTC, zero2080 commented on repository/freeBoardRepository.js
> +    }
잘 처리했습니다. 
하지만 이건 모든 연결에 해당합니다.
수행하는 쿼리에 상관없이 커넥션을 반환해야 합니다.
커넥션을 반환하지 않으면 풀에서 관리중인 커넥션이 소진됐을때 서버는 커넥션이 확보될때까지 DB연결을 지연시킬것입니다.

2024-01-11 08:30 UTC, zero2080 requested changes
관련 오류가 발생할 수 있는 부분을 모두 찾아서 수정해 주세요.

2024-01-11 08:30 UTC, zero2080 commented on controller/free_board.controller.js
> +        }
```suggestion
        if (decodedToken.id === selectRow.user_id) {
            const deleteRow = await freeBoardRepository.deleteFreeBoard(decodedToken, postId);

            if (deleteRow.affectedRows === 1) {
                res.status(200).json({ message: "게시글 삭제완료" });
            }
        }else{
            return res.status(403).json({ message : "권한이 없습니다"});
```

2024-01-11 08:47 UTC, zero2080 approved these changes
수고하셨습니다

2024-01-11 08:48 UTC, merged